<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Freely.Agent\Freely.Agent.csproj" />
    <ProjectReference Include="..\Freely.Computer\Freely.Computer.csproj" />
    <ProjectReference Include="..\Freely.Perception\Freely.Perception.csproj" />
  </ItemGroup>
</Project>
